# Generated by Django 2.1.5 on 2019-01-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_preview',
            field=models.TextField(null=True),
        ),
    ]
