# Generated by Django 2.1.5 on 2019-01-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_content_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_category',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='sub_category',
            field=models.CharField(default='test_sub_category', max_length=120),
            preserve_default=False,
        ),
    ]
