# Generated by Django 2.1.5 on 2019-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190119_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='article',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
