# Generated by Django 2.1.5 on 2019-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190129_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
