# Generated by Django 2.1.5 on 2019-01-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_article_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='main_category',
            new_name='category',
        ),
    ]
