# Generated by Django 2.1.5 on 2019-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190130_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topRecommended',
            field=models.BooleanField(default=False),
        ),
    ]
