# Generated by Django 2.1.5 on 2019-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190202_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_preview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobDescription_1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobDescription_2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobDescription_3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat_QR_code',
            field=models.URLField(default=''),
        ),
    ]
