# Generated by Django 2.1.5 on 2019-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190202_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
