# Generated by Django 2.1.5 on 2019-02-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190202_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_preview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobDescription_1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobDescription_2',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobDescription_3',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat_QR_code',
            field=models.URLField(blank=True),
        ),
    ]
