# Generated by Django 2.1.5 on 2019-02-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
