# Generated by Django 2.1.5 on 2019-10-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(verbose_name='website')),
                ('sector', models.CharField(max_length=50, null=True, verbose_name='sector')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='country')),
                ('symbol', models.CharField(max_length=50, null=True, verbose_name='symbol')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='company')),
                ('industry', models.CharField(max_length=50, null=True, verbose_name='industry')),
                ('CEO', models.CharField(max_length=50, null=True, verbose_name='CEO')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15, verbose_name='symbol')),
                ('userName', models.CharField(max_length=50, verbose_name='userName')),
                ('lastPrice', models.FloatField(verbose_name='lastPrice')),
                ('aChange', models.FloatField(verbose_name='aChange')),
                ('pChange', models.FloatField(verbose_name='pChange')),
                ('shares', models.FloatField(verbose_name='shares')),
                ('costBasis', models.FloatField(verbose_name='costBasis')),
                ('marketValue', models.FloatField(verbose_name='marketValue')),
                ('dGain', models.FloatField(verbose_name='dGain')),
                ('tGain', models.FloatField(verbose_name='tGain')),
                ('No', models.FloatField(verbose_name='No')),
                ('date', models.CharField(max_length=50, verbose_name='date')),
            ],
            options={
                'db_table': 'holding',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, null=True, verbose_name='symbol')),
                ('sector', models.CharField(max_length=50, null=True, verbose_name='sector')),
            ],
            options={
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15, verbose_name='symbol')),
                ('date', models.CharField(max_length=50, verbose_name='date')),
                ('start', models.FloatField(verbose_name='start')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('close', models.FloatField(verbose_name='close')),
                ('volume', models.BigIntegerField(default=0, verbose_name='volume')),
                ('split', models.FloatField(verbose_name='split')),
                ('dividend', models.FloatField(verbose_name='dividend')),
                ('aChange', models.FloatField(verbose_name='aChange')),
                ('pChange', models.FloatField(verbose_name='pChange')),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, null=True, verbose_name='symbol')),
            ],
            options={
                'db_table': 'symbols',
            },
        ),
    ]
