# Generated by Django 2.1.5 on 2019-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='No',
        ),
        migrations.AddField(
            model_name='holding',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
    ]
