# Generated by Django 2.1.5 on 2019-10-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20191029_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='aChange',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='costBasis',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='dGain',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='lastPrice',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='marketValue',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='pChange',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='tGain',
        ),
        migrations.AddField(
            model_name='holding',
            name='action',
            field=models.IntegerField(default=1, verbose_name='action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holding',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
            preserve_default=False,
        ),
    ]
