# Generated by Django 2.1.5 on 2019-11-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20191030_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
    ]
