# Generated by Django 2.1.5 on 2019-11-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_futureprediction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='futureprediction',
            table='FuturePrediction',
        ),
    ]
