# Generated by Django 2.1.5 on 2019-11-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20191105_0409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='futureprediction',
            table='futurePrediction',
        ),
    ]
