# Generated by Django 2.1.5 on 2019-11-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20191105_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userName', models.TextField(primary_key=True, serialize=False)),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('birthday', models.TextField()),
                ('budget', models.FloatField()),
            ],
        ),
    ]
